<?php

namespace ReclamationBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public function notuser()
    {
        $query=$this->getEntityManager()->createQuery("select u from FixitBundle:User u where u.roles!=:roles ")->setParameter('roles', 'ROLE_ADMIN');
        return $query->getResult();
    }
}
