fixit_homepage:
    path:     /home
    defaults: { _controller: FixitBundle:Default:index }
email_avaibility:
    path:     /userEmailVerification
    defaults: { _controller: FixitBundle:Registration:checkEmail }
fixit_admin:
    path:     /admin
    defaults: { _controller: FixitBundle:Default:admin }
fixit_contact:
    path:     /contact
    defaults: { _controller: FixitBundle:Default:contact }
fixit_about:
    path:     /about
    defaults: { _controller: FixitBundle:Default:about }
fixit_electricite:
    path:     /electricite
    defaults: { _controller: FixitBundle:Default:elect }
fixit_mec:
    path:     /mecanique
    defaults: { _controller: FixitBundle:Default:mec }
fixit_tel:
    path:     /tel
    defaults: { _controller: FixitBundle:Default:tel }
fixit_elecm:
    path:     /elecm
    defaults: { _controller: FixitBundle:Default:elecm }
fixit_plomberie:
    path:     /plom
    defaults: { _controller: FixitBundle:Default:plom }