services_categories:
    resource: "@ServicesBundle/Controller/CategoriesController.php"
    type:     annotation

services:
    resource: "@ServicesBundle/Resources/config/routing.yml"
    prefix:   /services

fixit:
    resource: "@FixitBundle/Resources/config/routing.yml"
    prefix:   /fixit

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"