news:
    resource: "@newsBundle/Resources/config/routing.yml"
    prefix:   /

fixit:
    resource: "@FixitBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"