<?php

namespace ServicesBundle\Repository;

/**
 * ServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbycategories(){
        $query = $this->getEntityManager()->createQuery("SELECT ev FROM ServicesBundle:Services ev WHERE ev.Categories LIKE ev.Categories = :libelle");
    }

    public function TopView()
    {
        $query=$this->getEntityManager()->createQuery("select u from FixitBundle:User u ORDER BY u.view DESC ");
        return $query->getResult();
    }
}
