<?php

namespace FixitBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

//    public function check_email_forSignUp($email)
//    {
//        $qb = $this->getEntityManager()->createQuery("SELECT user FROM
//             FixitBundle:user user where user.email=:email")
//            -> setParameters (array ('email'=> $email));
//        return $qb->getResult();
//    }

}
